# config.v8+.yaml

# General Snakemake settings
restart-times: 0
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 4
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True

# Executor settings
executor: "local"