restart-times: 0
local-cores: 16
latency-wait: 1440  # wait 2 minutes for missing files before raising exception
jobs: 8
keep-going: True
rerun-incomplete: True
printshellcmds: True

# Container and environment settings
use-singularity: True
singularity-args: "--nv --bind /Genomics/ayroleslab2/scott/micros:/Genomics/ayroleslab2/scott/micros"

# Set resources for specific rules
set-resources:
  run_sleap:
      n_jobs: 8
