restart-times: 0
local-cores: 1
latency-wait: 120  # wait 2 minutes for missing files before raising exception
jobs: 1
keep-going: True
rerun-incomplete: True
printshellcmds: True

# Container and environment settings
use-singularity: True
singularity-args: "--nv"
#
# Set resources for specific rules
set-resources:
  run_sleap:
      n_jobs: 1  # Limit the number of concurrent run_sleap jobs to 1
