executor: slurm

default-resources:
    runtime: 1440
    mem: "64G"
    cpus_per_task: 4

# General Snakemake settings
local-cores: 4
jobs: 120
keep-going: True
printshellcmds: True
scheduler: greedy

# Container and environment settings
use-singularity: True
singularity-args: "--nv"

# Rule-specific resource overrides
set-resources:
    run_sleap:
        runtime: 1440
        slurm_extra: "'--gres=gpu:1'"
        mem: "128G"
