executor: slurm

default-resources:
    runtime: 61
    mem: "64G"
    slurm_extra: "'--gres=gpu:1'"
# General Snakemake settings
local-cores: 4
jobs: 20
keep-going: True
printshellcmds: True
scheduler: greedy

# Container and environment settings
use-singularity: True
singularity-args: "--nv"
