executor: slurm

default-resources:
    runtime: 61
    mem_mb_per_cpu: 4096
    cpus_per_task: 4

set-resources:
    run_sleap:
        runtime: 61
        mem_mb_per_cpu: 4096
        cpus_per_task: 4
        slurm_extra: "'--gres=gpu:1'"

# General Snakemake settings
restart-times: 0
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 2
latency-wait: 60
jobs: 100
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True